name: Download data views from GCP BigQuery

on:
  workflow_dispatch:
  repository_dispatch:
    types: ["download"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3.1.2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.7.0
        with:
          credentials_json: ${{secrets.GCP_CREDENTIALS}}
          export_environment_variables: true

      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run download python file
        run: python3 scripts/GHQueryForViewData.py

      - name: Commit new files
        run: |
          git config --global user.name 'wordle-tweet-bot'
          git config --global user.email 'wordle-tweet-bot@users.noreply.github.com'
          git add data_views/.
          git commit -am "Adding Data for Wordle ${{github.event.client_payload.wordle_num}}"
          git push
