name: Run the twitter API script for the days wordle tweets

on:
  workflow_dispatch:
  schedule:
    - cron: "35 1 * * *"

env:
  BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout wordle-twitter-stats repo
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.7.0
        with:
          credentials_json: ${{secrets.GCP_CREDENTIALS}}
          export_environment_variables: true

      - name: Setup Python
        uses: actions/setup-python@v3.0.0

      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tweet API python file
        run: python3 scripts/WordleTwitterAPIScrape.py latest github

      - name: Upload data file to google cloud storage
        uses: "google-github-actions/upload-cloud-storage@v0"
        with:
          path: "${{env.WORDLE_DATA_FILEPATH}}"
          destination: "wordle-twitter-data-main/day_files/"
          gzip: false
